### ISSUE TITLE
How to add a new module/library in G3W-ADMIN?

### ISSUE THREAD

**Issue by bard0x** [g3w-suite/g3w-admin#428]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Hello,

if I want to add a new library in g3w-admin via pypy.org for example this one https://pypi.org/project/django-cookies-samesite how can I do it?

Thanks in advance

### Steps to reproduce

Described above

### Environment

- g3w-admin: v3.5-dev
- browser: chrome
- operating system: ubuntu

**Comment by wlorenzetti** [comment]
G3W-ADMIN is a Django application and behaves like one. If you want to add a Python module or package using pip, at the dockerization level you just need to add the package and possibly the required version inside the [requirements_rl.txt](https://github.com/g3w-suite/g3w-suite-docker/blob/dev/requirements_rl.txt)

**Comment by Raruto** [comment]
@wlorenzetti @bard0x I just point out that at the moment with the **g3w-suite-docker@v3.5** to do this through the `requirements_rl.txt` it is very likely that you have to rebuild the docker image you are working on (ref: [Dockerfile.g3wsuite.dockerfile#L27-L28](https://github.com/g3w-suite/g3w-suite-docker/blob/9475d8260979309e9e583a951306326b016247ea/Dockerfile.g3wsuite.dockerfile#L27-L28)).

Anyway for quick testing, you can just follow the instructions given by the specific package, ie. within a terminal shell run:

```
pip install django-cookies-samesite
```

Refer to the [exec](https://docs.docker.com/engine/reference/commandline/exec/) command to understand how it can be used in a docker shell.

---

@bard0x please note that this is an issue tracker whose readers use **`English`** as their main speak language, in the future please create reports adopting this standard (otherwise they are quite useless for anyone else who would like to help you and for anyone searching among previous issues).

In addition, please not use the `g3w-admin: dev` version as a reference for your reports, but instead always indicate the full version you are having trouble (eg. `g3w-admin: 3.5.dev-20221221144945`). Bear with me, but without this precise information your report is practically useless..

If in doubt, you can just go to the admin dashboard to get exact version:

![dashboard](https://user-images.githubusercontent.com/9614886/208938762-afb48591-c249-4868-89f1-c44e85b91c65.png)

_Thank you in advance for your patience and cooperation,
Raruto_
