### ISSUE TITLE
Update Language

### ISSUE THREAD

**Issue by abrousseau89** [g3w-suite/g3w-admin#510]
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

Good morning,

Is there a solution to help with the translation of the different menus in the administration part of G3wSuite?

### Suggested solution

If I can help for the French?
Thanks

**Comment by wlorenzetti** [comment]
Hi @abrousseau89 sure, you can contribute making a Pull Request with files `*.po` updated.
Here you can update translations file for G3W-ADMIN make an update of *.po files that you can find inside the g3w-admin module, i.e. for `core` you can update the https://github.com/g3w-suite/g3w-admin/blob/dev/g3w-admin/core/locale/fr/LC_MESSAGES/django.po for French language.

If you want contribute also to G3W-CLIENT (webgis) you have to open a issue like that to https://github.com/g3w-suite/g3w-client/issues, because for G3W-CLIENT the translations system is different.

**Comment by abrousseau89** [comment]
Thx, i will try
