### ISSUE TITLE
Attribute editing: Checkbox widget

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#958]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

Manage the option:

Use True/False instead of stored value

### Steps to reproduce

QGIS example

![Image](https://github.com/user-attachments/assets/73a38e47-e6ea-4e3f-af4a-628419f5bf2a)

The True/False values ​​must be displayed instead of the values ​​present in the data:

- at the editing level
- at the query level
- in the attribute table
- in research

### Environment

v3.9

**Comment by Raruto** [comment]
![image](https://github.com/user-attachments/assets/846885d0-f2cd-428d-be49-8ec8a4e6c875)

@leolami an issue it's either a `bug` or a `feature`, it can't be both.

Please try to keep that concepts separate, otherwise it gets messy.

Generally speaking:

- it's a new `feature` request: when something is not yet implemented (or it works slightly differently from QGIS Desktop).
- it's a `bug`: when we have a software regression (from a previous G3W-SUITE version) of features that had been implemented

👋 Raruto

**Comment by volterra79** [comment]
@wlorenzetti this is the current configuration for checkbox widget:

```
{
    "name": "safety_exits",
    "type": "varchar",
    "label": "Safety exits",
    "editable": true,
    "validate": {},
    "pk": false,
    "default": "",
    "input": {
        "type": "check",
        "options": {
            "values": [
                {
                    "value": "Checked",
                    "checked": true
                },
                {
                    "value": "Not checked",
                    "checked": false
                }
            ]
        }
    }
}
```
I think we need just another for item values (ex **label**)
```

"options": {
            "values": [
                {
                    "value": "Checked",
                    "checked": true,
                    "label": "True"
                },
                {
                    "value": "Not checked",
                    "checked": false,
                    "label": "False"

                }
            ]
        }
```
